updates the step-1 and step-2 with appropriate information
icyflame/leprechaun pull request #2
Opened 2018-01-06 07:56 UTC by sangeet259

1. Adds how to add the necessary verifier text in the ERP question!
2. The mail by Leprechaun lands in spam folders sometimes, this PR adds this info in the step-2 page.

2018-01-06 08:17 UTC, icyflame requested changes

2018-01-06 08:17 UTC, icyflame commented on templates/step1_complete.tmpl.html
> +                    Note : Check your spam and promotions if the mail is not in your primary space!
Put `Note:` under `<b></b>`

2018-01-06 08:17 UTC, icyflame commented on templates/begin_auth.tmpl.html
> +                        <li>Enter 3 questions, anyone of which must be {{.Verifier}}. It's answer can be anything.</li>
```html
<li>
    any one of the three questions must contain {{.Verifier}}.
    <br>
    <b>Pro-Tip:</b> Enter your old question followed by {{.Verifier}}!
    <br>
    Eg: Original question: <i>What was the name of your first pet?</i>
    <br>
    Required question: <i>What was the name of your first pet? {{.Verifier}}</i>
</li>
```

2018-01-06 08:17 UTC, icyflame commented on templates/begin_auth.tmpl.html
> +                    To do that :
We shouldn't put this information inside `div.jumbotron`. Put it after this div.

2018-01-06 08:36 UTC, sangeet259 commented
@icyflame changes made

2018-01-09 10:37 UTC, closed without merging

2018-01-09 10:44 UTC, icyflame commented
Hey @sangeet259, thanks for your changes. I have merged them in. I put the guide text outside the jumbotron and added a note about the guide in the jumbotron.

There are definitely other enhancements that can be made on the user-facing side of this module. If you have the time, you can review the other templates in this flow and send patches as you see fit. I will be happy to accept them. :slightly_smiling_face:

2018-01-09 10:54 UTC, sangeet259 commented
Sure @icyflame :+1: